/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package school.managemnet.system;

import org.junit.jupiter.api.Test;

import app.src.main.java.school.managemnet.system.Program.SchoolManagementSystem;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        SchoolManagementSystem program = new SchoolManagementSystem();
        assertNotNull(program.Test(), "app should have a greeting");
    }
}
